---
- hosts: all
  tasks:
  - name: install memcached Ubuntu
    apt: pkg=memcached state=installed
    when: ansible_pkg_mgr == "apt"
  - name: install memcached CentOS
    yum: name=memcached state=installed
    when: ansible_pkg_mgr == "yum"
  - name: create memcached config dir
    command: mkdir -p /data/services/memcached/conf
  - name: create memcached init script
    copy: src={{ init_script }} dest=/etc/init.d/memcached owner=root group=root mode=0755
    
   
  
  
  
  